# Generated by Django 2.2.5 on 2019-09-23 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_vacancy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('vacancies_accept', models.ManyToManyField(blank=True, related_name='accept_for_resume', to='client.Vacancy')),
                ('vacancies_in_waiting', models.ManyToManyField(blank=True, related_name='in_waiting_for_resume', to='client.Vacancy')),
                ('vacancies_reject', models.ManyToManyField(blank=True, related_name='reject_for_resume', to='client.Vacancy')),
            ],
        ),
    ]
